### ISSUE TITLE
Error using 1.8

### ISSUE THREAD

**Issue by NathanSweet** [ReFlar/pwned-passwords#30]
## Bug Report

I see this occasionally in my log:

```
[2023-09-19 14:53:32] flarum.ERROR: Error: Class "Flarum\User\Command\RequestPasswordReset" not found in /flarum/vendor/fof/pwned-passwords/src/Middleware/CheckLoginPassword.php:73
Stack trace:
#0 /flarum/vendor/laminas/laminas-stratigility/src/Next.php(49): FoF\PwnedPasswords\Middleware\CheckLoginPassword->process()
#1 /flarum/vendor/fof/pwned-passwords/src/Middleware/PreventPwnedPassword.php(62): Laminas\Stratigility\Next->handle()
```

I don't know how it is triggered though. I can create a new account and request a password reset without causing this.

It appears `Flarum\User\Command\RequestPasswordReset` is not a class in 1.8:
https://api.docs.flarum.org/php/v1.8.0/flarum/user/command

**Comment by imorland** [comment]
`Flarum\User\Command\RequestPasswordReset` was removed in Flarum 1.6 - https://github.com/flarum/framework/pull/3616 and moved to a queue job, so this has been an issue for a while 🙈 

I'll push a patch for this today
